call DATA_WARE_HOUSE.BRONZE.DWH_LOAD_CRM_DATA();
CREATE OR REPLACE PROCEDURE DATA_WARE_HOUSE.BRONZE.DWH_LOAD_CRM_DATA()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN

    -- CRM Customer Info
    TRUNCATE TABLE BRONZE.CRM_CUST_INFO;
    COPY INTO BRONZE.CRM_CUST_INFO
    FROM @DWH_S3/cust_info.csv
    FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
    ON_ERROR = 'CONTINUE';

    -- CRM Product Info
    TRUNCATE TABLE BRONZE.CRM_PRD_INFO;
    COPY INTO BRONZE.CRM_PRD_INFO
    FROM @DWH_S3/prd_info.csv
    FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
    ON_ERROR = 'CONTINUE';

    -- CRM Sales Details
    TRUNCATE TABLE BRONZE.CRM_SALES_DETAILS;
    COPY INTO BRONZE.CRM_SALES_DETAILS
    FROM @DWH_S3/sales_details.csv
    FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
    ON_ERROR = 'CONTINUE';

    -- ERP LOC A101
    TRUNCATE TABLE BRONZE.ERP_LOC_A101;
    COPY INTO BRONZE.ERP_LOC_A101
    FROM @DWH_S3/LOC_A101.csv
    FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
    ON_ERROR = 'CONTINUE';

    -- ERP PX CAT G1V2
    TRUNCATE TABLE BRONZE.ERP_PX_CAT_G1V2;
    COPY INTO BRONZE.ERP_PX_CAT_G1V2
    FROM @DWH_S3/PX_CAT_G1V2.csv
    FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
    ON_ERROR = 'CONTINUE';

    -- ERP Customer AZ12
    TRUNCATE TABLE BRONZE.ERP_CUST_AZ12;
    COPY INTO BRONZE.ERP_CUST_AZ12
    FROM @DWH_S3/CUST_AZ12.csv
    FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1)
    ON_ERROR = 'CONTINUE';

    RETURN 'CRM data loaded successfully into bronze layer';

END;
$$;
