    
CREATE OR REPLACE TASK task_silver_load
WAREHOUSE = COMPUTE_WH
AFTER LOAD_CRM_DATA_TASK
AS
CALL DATA_WARE_HOUSE.SILVER.DWH_DATA_LOAD_SILVER();

ALTER TASK bronze.LOAD_CRM_DATA_TASK suspend;

show tasks;

ALTER TASK bronze.LOAD_CRM_DATA_INTO_DWH RESUME;
ALTER TASK bronze.LOAD_CRM_DATA_TASK RESUME;
ALTER TASK task_silver_load RESUME;
